kind: pipeline
name: default

steps:
  - name: build
    image: node:6
    commands:
      - npm install
      - bash ./ci/gh-pages.sh
    environment:
      DECRYPT_KEY:
        from_secret: "DECRYPT_KEY"
      COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
      DEPLOY_DIR: "public"
    when:
      branch:
        - master
